CREATE DATABASE FIRST_SITE
USE FIRST_SITE

CREATE TABLE SLIDERS 
(
ID INT PRIMARY KEY IDENTITY,
Title NVARCHAR(50)NOT NULL,
Text NVARCHAR (100) NOT NULL,
Image NVARCHAR (25) NOT NULL,
[Order] INT NOT NULL

)

CREATE TABLE CATEGORIES
(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (15)
)

CREATE TABLE PRODUCTS 
(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(15) NOT NULL,
Price DECIMAL NOT NULL,
CategoryId int CONSTRAINT FK_CHECK_CI FOREIGN KEY REFERENCES CATEGORIES(ID) ,
DiscountAmount DECIMAL ,
IsNEW BIT ,
PrCount int ,
[DESC] NVARCHAR(15) NOT NULL,
CODE NVARCHAR(10) NOT NULL,
CostPrice DECIMAL
)
CREATE TABLE TAGS
(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (10) NOT NULL

)
CREATE TABLE ProductTags
(
ID INT PRIMARY KEY IDENTITY,
ProductID INT FOREIGN KEY REFERENCES PRODUCTS(ID),
TagsId INT FOREIGN KEY REFERENCES TAGS(ID)

)

CREATE TABLE USERS 
(
ID INT PRIMARY KEY IDENTITY,
FullName NVARCHAR (15) NOT NULL,
EMAIL NVARCHAR (100) NOT NULL,
IMAGE NVARCHAR (150) NOT NULL,
PasHash NVARCHAR(200) NOT NULL,
Address NVARCHAR (250) NOT NULL
)

CREATE TABLE REWIEVS
(
ID INT PRIMARY KEY IDENTITY,
ProductID INT FOREIGN KEY REFERENCES PRODUCTS(ID)  ,
UserId INT FOREIGN KEY REFERENCES USERS(ID),
Name NVARCHAR (35),
Email NVARCHAR (100),
Text NVARCHAR (200),
CreatedAt DATETIME2
)

CREATE TABLE Orders
(
ID INT PRIMARY KEY IDENTITY,
UserId INT FOREIGN KEY REFERENCES USERS(ID),
CreatedAt DATETIME2,
DeliveredAt DATETIME2,
Status TINYINT,
PaymentStatus TINYINT,
TotalAMount DECIMAL,
Address NVARCHAR(200),
Email NVARCHAR (100),
FullName NVARCHAR (15) NOT NULL,
)
CREATE TABLE OrderItems
(
ID INT PRIMARY KEY IDENTITY,
ProductID INT FOREIGN KEY REFERENCES PRODUCTS(ID)  ,
OrderId INT FOREIGN KEY REFERENCES Orders(ID)  ,
[Count] INT ,
Price INT,
DiscountAmount DECIMAL,
CostPrice INT
)
CREATE TABLE ProductImages
(
ID INT PRIMARY KEY IDENTITY,
ProductID INT FOREIGN KEY REFERENCES PRODUCTS(ID),
Image NVARCHAR(200)

)
CREATE TABLE AdditionalInfoTypes
(
ID INT PRIMARY KEY IDENTITY,
Name NVARCHAR(150)

)
CREATE TABLE AdditionalInfos
(
ID INT PRIMARY KEY IDENTITY,
ProductID INT FOREIGN KEY REFERENCES PRODUCTS(ID),
Value NVARCHAR(150),
AdditionalInfoTypes INT FOREIGN KEY REFERENCES AdditionalInfoTypes(ID),

)