CREATE DATABASE IMDB
USE IMDB

CREATE TABLE MOVIES 
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(10) NOT NULL,
ReleaseData DATETIME DEFAULT(GETDATE()),
Duration INT NOT NULL CHECK(DURATION>0),
Description NVARCHAR(100),
ImdbPoint INT NOT  NULL
)


ALTER TABLE MOVIES
ADD FOREIGN KEY  (DirectoryID)   REFERENCES  Directors(ID)


CREATE TABLE GENRES 
(
ID INT PRIMARY KEY IDENTITY,
GenreName NVARCHAR(15)
)

CREATE TABLE MoviesGenres 
(
ID INT PRIMARY KEY IDENTITY,
MoviesID INT CONSTRAINT Mv_Check FOREIGN KEY  REFERENCES  MOVIES(ID),
Genres INT CONSTRAINT GN_Check FOREIGN KEY  REFERENCES  GENRES(ID),
)

CREATE TABLE Directors
(
ID INT PRIMARY KEY IDENTITY,
FullName NVARCHAR(10) NOT NULL,
)
CREATE TABLE Actors
(
ID INT PRIMARY KEY IDENTITY,
FullName NVARCHAR(10) NOT NULL,
)

CREATE TABLE MoviesActors
(
ID INT PRIMARY KEY IDENTITY,
MovieID INT CONSTRAINT Movie_Check FOREIGN KEY  REFERENCES  MOVIES(ID),
ActorID INT CONSTRAINT AC_Check FOREIGN KEY  REFERENCES  Actors(ID),
)
CREATE TABLE MovieImages
(
ID INT PRIMARY KEY IDENTITY,
Name NVARCHAR(10) NOT NULL,
MoviesID INT CONSTRAINT  Check_id FOREIGN KEY  REFERENCES  MOVIES(ID),
)

SELECT M.Name,M.ImdbPoint,G.GenreName,D.FullName,A.FullName FROM MOVIES AS M
FULL OUTER JOIN Genres AS G ON M.Name=G.GenreName
FULL OUTER JOIN Directors AS D ON M.Name=D.FullName
FULL OUTER JOIN Actors AS A ON m.Name=A.FullName